### ISSUE TITLE
[Bug]: Images are unable to be downloaded from some sites due to missing user-agents

### ISSUE THREAD

**Issue by Josh5** [Josh5/TVH-IPTV-Config#14]
### Describe the Bug

Eg:
```
2024-06-28 23:10:28,555:ERROR:werkzeug.channels: An error occurred while updating channel image: 403 Client Error: Forbidden. Please comply with the User-Agent policy: https://meta.wikimedia.org/wiki/User-Agent_policy for url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/FS2_logo_2015.svg/192px-FS2_logo_2015.svg.png
```

### Version

latest

**Comment by P-yiush07** [comment]
can you tell the steps to reproduce it ?

**Comment by Josh5** [comment]
Add an image from a site like above. `https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/FS2_logo_2015.svg/192px-FS2_logo_2015.svg.png`

Add this as a channel logo

**Comment by Josh5** [comment]
This will be fixed in a few mins. Just re-writing the functions that handle this download

**Comment by P-yiush07** [comment]
heyy i want to do some open source contributions, will you let me do a contribution ?

**Comment by Josh5** [comment]
> heyy i want to do some open source contributions, will you let me do a contribution ?

Absolutely!
Join me on Discord and we can have a chat:

https://streamingtech.co.nz/discord

Message me (Josh.5) on the "tvh-iptv-config" channel
